# Generated by Django 6.0.4 on 2026-05-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import runs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        default=runs.models.gen_invite_code, max_length=6, unique=True
                    ),
                ),
                ("is_started", models.BooleanField(default=False)),
                ("template_config", models.JSONField()),
                ("current_config", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
