# Generated by Django 6.0.4 on 2026-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='participants',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='run',
            name='pending_players',
            field=models.JSONField(default=list),
        ),
    ]
