# Generated by Django 6.0.4 on 2026-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_run_participants_run_pending_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='pending_claims',
            field=models.JSONField(default=list),
        ),
    ]
